### PR TITLE
Load BMS file and nosecone catalog 

### PR DESCRIPTION
**Pull request by ghost**
Load BMS file and nosecone catalog ,

### CODE REVIEW

**Comment by dbcook** [comment]
Finally got a couple of hours to go through this.  There are a couple of things to do, one big, and a couple smaller.
1.  Let's take the Rocketarium file out of this PR and put it in an independent PR. (the easy one)
2. All the <description> tags need to be conformed to the most-to-least significant organization established in the other major files and that is specified at about L#962 in the README.  For example, a typical BT-20 nose cone description should look like "Nose cone, balsa, BT-20, 3.0", elliptical, PN BNC-20AH".  The full dimensions don't need to be in there because you can see them in other columns of the dialog.  The manufacturer's description shouldn't be used because they don't follow this prescription and are often very irregular.  Following this standard means that if you first filter to a given manufacturer and then sort on the description column, they will sort to a sensible order by material, tube series and length.
3. There are several material tags in the BMS file for body tubes of different sizes.  Kraft paper density from the same tube producer will be reasonably uniform, with some variation batch to batch.  I think we should just use one density value per mfr for the same type of tube.  A few years ago I computed average densities of Estes and LOC tubes and got values in the mid 800s that were quite close to published paper industry densities for thin-wall kraft glassine.  Sadly I think the density analysis spreadsheet with data I pulled from Estes and Apogee was lost with my fried computer.

**Comment by ghost** [comment]
#1 I agree
#2 We are going to have to disagree with you., Per your example., "Nose cone, balsa, BT-20, 3.0", elliptical, PN BNC-20AH". The Nose cone is redundant because we would not even see it if we choose nose cones from the parts list. Balsa, BT-20 and elliptical I agree with, except that in most case the shape is not specified, and I don't want to guess. The PN in the description is totally redundant as there is a xml field for this and conveys no new information. I included it in most cases to be consistent, but I really think it need to be gone.
#3 Would have been helpful before doing this, I still don't have these average densities, therefore, I endeavored to get as close to the weights provided by BMS. I did the same for the Rocketarium parts.I think that being on the side of more accurate is good. Maybe trivial, but better. I did see some of these being up to 1 oz. off.

**Comment by dbcook** [comment]
There are detailed reasons for everything in the description field.  I've
been through about four iterations of it over the last 5 years to try to
make everything look and act right in the selection dialogs.

   - A basic point about the description fields is that consistency is
   mandatory.  The reason is that if we ever want to change the layout again,
   being able to use a script is a must.  The previous manual layout changes I
   made were when the database was considerably smaller, and they took days of
   work.  There are now perhaps 6000 parts overall and a manual conversion is
   really no longer feasible.
   - Item type, e.g. "Nose cone".  This is present because there are a
   number of items where the intended use is different from the OR tag type.
   See for example Estes PNC-3, LOC PNC-3.90-V2, etc.
   - The NC and transition shapes ALWAYS have to be specified, Principles:
   *a) *OR requires it for its calculations.  b)  *Safety issue*.  *Nose
   cones etc. where the manufacturer doesn't specify the shape should not be
   included in the database since the CG, Cd and moments of inertia depend on
   the shape.  For HPR, differences in Cd and CG due to shape can noticeably
   affect stability and that is a major safety issue.*  For liability
   reasons I will absolutely not list parts where there is an ambiguity in
   the manufacturer's data that could result in unexpected instability.  It is
   OK to determine the shape by eyeball if the mfr provides a drawing or photo.
   - The PN is not redundant.  Principle: *non-identical parts from the
   same manufacturer shall not have an identical description.  *It is there
   to provide a deterministic sort order for the description column in cases
   where a part with an otherwise identical basic description gets some
   manufacturing change that does not affect the base description, but it
   acquires a new PN. A further tag that has sometimes been applied more
   recently is a year-of-data tag; that comes into play when a given part has
   a spec change like OD, mass, etc. but is *not* given a new PN.
   - Tube density.  Principle: *manufacturer mass data is often
   untrustworthy.  *The historical record has been that the manufacturers
   are really sloppy about weighing things.  Carl McLawhorn (Mr. Semroc) once
   told me that he believed that Estes originally used a postal scale to weigh
   things and that most of their weights for nose cones, small tubes,
   and similar parts were highly suspect.  Same for LOC in the first two
   administrations; I found much better mass data on the Apogee website,
   because Tim Van Milligan carefully weighed a lot of things for their
   store.  Thus I totally would not try to match the individual quoted weights
   for the BMS tubes.  Actual masses from real samples would be OK, but I'd
   use them to compute an average density, not ones customized for each tube
   size.  The manufacturing reality is that BMS gets their tubes from the same
   source, and the manufacturing materials and processes are identical (at
   least across one manufacturing run).  So there is no physical reason to
   believe that material density would vary significantly by tube size.
   - I do have examples of a few BMS tube sizes that I could check - I've
   got a fair number of 13mm and 18mm 34" tubes, and also some BTH-80 and
   BT-70.  In an evening I could come up with a decent average density based
   on having both small and larger tubes to weigh.  Unfortunately all this
   material is inaccessible until the rest of my house is done with the
   rebuild.
   - The standard practice is to curate all densities into
   generic_materials.orc, and the individual .orc files may *only* use
   values pasted in from generic_materials.orc.  Someday I hope the code devs
   will give us a #include facility.  I spent a ton of time rectifying
   inconsistent and often inaccurate one-off material defs in the old OR
   files.

**Comment by ghost** [comment]
I still disagree with most of this. While you don't have densities based on tube size you do have it based on manufacturer. How do I know what to choose or how to create my own. I have already completed the BMS file and I am 95% complete with the Rocketarium.

**Comment by dbcook** [comment]
The densities differ per vendor because they have different upstream actual
tube makers with varying materials and processes.  There are literally
hundreds of different tube sizes (see the tube data files and spreadsheet)
and it doesn't make sense to maintain a density value for each one.

It would be perfectly fine, until we have real measured data, to use the
generic kraft/glassine density "Paper, spiral/glassine tubing, thin wall,
.849 g/cm3, bulk" for the normal wall thickness tubes and the thick-wall
version (769) for the heavy ones like the 80H.

For both densities and descriptions, at this point the standardization has
to be paramount, for reasons I explained above.  The data you've gathered
is really valuable and I'm going to merge the PR into a feature branch, but
to get it into release it will need to be made structurally consistent with
the rest of the files.  I *think* that a script can be made to do this
pretty easily.  Meanwhile I figured out where my BMS tubes are and I'll try
to retrieve them this week to get some measurements.

**Comment by ghost** [comment]
<"Paper, spiral/glassine tubing, thin wall,
.849 g/cm3, bulk" for the normal wall thickness tubes and the thick-wall
version (769) for the heavy ones like the 80H.>
Does it make sense that the heavy tubes have less density than the regular tubes?

As for the descriptions, I just look at them and honestly, it looks to me just like you describe, so I don't know what you are asking.

Talking to some of the OR devs the betas will be closing down soon, at least in the opinion of the devs I talked to. It is important that we get some data in these releases so we can get some feedback. 

I am feeling a little put upon and not feeling very valued at the moment. I spent several weeks building the BMS fie with very little direction only to be told now that it is not good enough to release.

**Comment by SiboVG** [comment]
> Talking to some of the OR devs the betas will be closing down soon, at least in the opinion of the devs I talked to. It is important that we get some data in these releases so we can get some feedback.

We know you wanted to have this included in the next OR release and we have certainly not forgotten about it. My guess is that we will be putting out the final release in about 2 months, give or take. So you still have some time.

We really appreciate your hard effort on this, seeing how extensive this PR has gotten, I can only respect you for it!

**Pull request merged**
